name: code validation
run-name: code validation triggered by ${{ github.actor }}
on: 
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  SNYK_SEVERITY_THRESHOLD: medium
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master

      - name: static code check
        run: |
             snyk code test --report --severity-threshold=$SNYK_SEVERITY_THRESHOLD --all-projects

  snyk-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/iac@master

      - name: iac code check
        run: |
             snyk iac test --report --severity-threshold=$SNYK_SEVERITY_THRESHOLD

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: code quality check
        uses: SonarSource/sonarcloud-github-action@master
