name: code validation
run-name: code validation triggered by ${{ github.actor }}
on: 
  workflow_call:



jobs:
  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master

      - name: static code check
        run: |
             snyk code test --report --severity-threshold=$SNYK_SEVERITY_THRESHOLD --all-projects

  snyk-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: iac code check
        uses: snyk/actions/iac@master
        with:
          args: --report --severity-threshold=$SNYK_SEVERITY_THRESHOLD

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: code quality check
        uses: SonarSource/sonarcloud-github-action@master
