name: deploy
run-name: deploy triggered by ${{ github.actor }}
on: 
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  SNYK_SEVERITY_THRESHOLD: medium
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
jobs:
  code_validation:
    uses: ./.github/workflows/code_validation.yml
