name: Code Validation
run-name: code validation triggered by ${{ github.actor }}
on: 
  pull_request:
    types: [ opened ]
    branches: [ main, master ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run Snyk for IAC
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --scan=resource-changes --report